version: '3.8'

services:
  mongo-service:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis-service:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo-service
      - redis-service

  frontend:
    build: ./frontend
    container_name: frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mongo_data:
